### ISSUE TITLE
DB Design

### ISSUE THREAD

**Issue by mehalyna** [ita-social-projects/Forum-Sandbox#2]

**Comment by pythonStudent88** [comment]
I suggest to add following items: 
region
image

/

![Image](https://github.com/ita-social-projects/Forum-Sandbox/assets/125041382/609c3136-c333-4265-b755-688ad8f7b1aa)

**Comment by BelousSofiya** [comment]
What about logo and banner_image? Will you cut them from this one image or they will be other pictures (and items)?

**Comment by BelousSofiya** [comment]
> I suggest to add following items:
> 
> * region
> * image
> 
> ![Image](https://user-images.githubusercontent.com/125041382/283573402-609c3136-c333-4265-b755-688ad8f7b1aa.png)

**Comment by BelousSofiya** [comment]
What about logo and banner_image? Will you cut them from this one image or they will be other pictures (and items)?
And region. Will it be city, administrative district, geographical district, etc.?

**Comment by romanmyko** [comment]
New logic db

**Comment by pythonStudent88** [comment]
my final suggestion is 

https://github.com/ita-social-projects/Forum-Sandbox/blob/documentation/db_schema.pdf
